/**
 * Avatares estáticos em /public/avatars — escolha no cadastro de usuário (MVP).
 */
export const AVATARES_PREDEFINIDOS = [
  { id: '1', url: '/avatars/avatar-1.svg', rotulo: 'Estilo 1' },
  { id: '2', url: '/avatars/avatar-2.svg', rotulo: 'Estilo 2' },
  { id: '3', url: '/avatars/avatar-3.svg', rotulo: 'Estilo 3' },
  { id: '4', url: '/avatars/avatar-4.svg', rotulo: 'Estilo 4' },
  { id: '5', url: '/avatars/avatar-5.svg', rotulo: 'Estilo 5' },
  { id: '6', url: '/avatars/avatar-6.svg', rotulo: 'Estilo 6' },
  { id: '7', url: '/avatars/avatar-7.svg', rotulo: 'Estilo 7' },
  { id: '8', url: '/avatars/avatar-8.svg', rotulo: 'Estilo 8' },
  { id: '9', url: '/avatars/avatar-9.svg', rotulo: 'Estilo 9' },
  { id: '10', url: '/avatars/avatar-10.svg', rotulo: 'Estilo 10' },
  { id: '11', url: '/avatars/avatar-11.svg', rotulo: 'Estilo 11' },
  { id: '12', url: '/avatars/avatar-12.svg', rotulo: 'Estilo 12' },
  { id: '13', url: '/avatars/avatar-13.svg', rotulo: 'Herói noturno' },
  { id: '14', url: '/avatars/avatar-14.svg', rotulo: 'Herói estelar' },
  { id: '15', url: '/avatars/avatar-15.svg', rotulo: 'Herói relâmpago' },
  { id: '16', url: '/avatars/avatar-16.svg', rotulo: 'Herói esmeralda' },
  { id: '17', url: '/avatars/avatar-17.svg', rotulo: 'Herói de armadura' },
  { id: '18', url: '/avatars/avatar-18.svg', rotulo: 'Herói aracnídeo' },
  { id: '19', url: '/avatars/avatar-19.svg', rotulo: 'Guardião celeste' },
  { id: '20', url: '/avatars/avatar-20.svg', rotulo: 'Vigia da noite' },
  { id: '21', url: '/avatars/avatar-21.svg', rotulo: 'Guerreira dourada' },
  { id: '22', url: '/avatars/avatar-22.svg', rotulo: 'Velocista carmesim' },
  { id: '23', url: '/avatars/avatar-23.svg', rotulo: 'Soberano aquático' },
  { id: '24', url: '/avatars/avatar-24.svg', rotulo: 'Sentinela verde' },
  { id: '25', url: '/avatars/avatar-25.svg', rotulo: 'Raposa' },
  { id: '26', url: '/avatars/avatar-26.svg', rotulo: 'Panda' },
  { id: '27', url: '/avatars/avatar-27.svg', rotulo: 'Pinguim' },
  { id: '28', url: '/avatars/avatar-28.svg', rotulo: 'Coruja' },
  { id: '29', url: '/avatars/avatar-29.svg', rotulo: 'Leão' },
  { id: '30', url: '/avatars/avatar-30.svg', rotulo: 'Sapo' },
  { id: '31', url: '/avatars/avatar-31.svg', rotulo: 'Pizza' },
  { id: '32', url: '/avatars/avatar-32.svg', rotulo: 'Hambúrguer' },
  { id: '33', url: '/avatars/avatar-33.svg', rotulo: 'Taco' },
  { id: '34', url: '/avatars/avatar-34.svg', rotulo: 'Melancia' },
  { id: '35', url: '/avatars/avatar-35.svg', rotulo: 'Cupcake' },
  { id: '36', url: '/avatars/avatar-36.svg', rotulo: 'Donut' },
  { id: '37', url: '/avatars/avatar-37.svg', rotulo: 'Abacate' },
  { id: '38', url: '/avatars/avatar-38.svg', rotulo: 'Sorvete' },
  { id: '39', url: '/avatars/avatar-39.svg', rotulo: 'Castelo encantado' },
  { id: '40', url: '/avatars/avatar-40.svg', rotulo: 'Varinha mágica' },
  { id: '41', url: '/avatars/avatar-41.svg', rotulo: 'Aventureira do mar' },
  { id: '42', url: '/avatars/avatar-42.svg', rotulo: 'Reino de gelo' },
  { id: '43', url: '/avatars/avatar-43.svg', rotulo: 'Xerife cowboy' },
  { id: '44', url: '/avatars/avatar-44.svg', rotulo: 'Defensor orbital' },
  { id: '45', url: '/avatars/avatar-45.svg', rotulo: 'Fada dos desejos' },
  { id: '46', url: '/avatars/avatar-46.svg', rotulo: 'Ratinho simpático' },
  { id: '47', url: '/avatars/avatar-47.svg', rotulo: 'Gato relâmpago' },
  { id: '48', url: '/avatars/avatar-48.svg', rotulo: 'Gato da noite' },
  { id: '49', url: '/avatars/avatar-49.svg', rotulo: 'Gato celeste' },
  { id: '50', url: '/avatars/avatar-50.svg', rotulo: 'Gato esmeralda' },
  { id: '51', url: '/avatars/avatar-51.svg', rotulo: 'Gato estelar' },
  { id: '52', url: '/avatars/avatar-52.svg', rotulo: 'Gato invicto' },
  { id: '53', url: '/avatars/avatar-53.svg', rotulo: 'Gato das marés' },
  { id: '54', url: '/avatars/avatar-54.svg', rotulo: 'Gato solar' },
  { id: '55', url: '/avatars/avatar-55.svg', rotulo: 'Golden feliz' },
  { id: '56', url: '/avatars/avatar-56.svg', rotulo: 'Dálmata' },
  { id: '57', url: '/avatars/avatar-57.svg', rotulo: 'Corgi' },
  { id: '58', url: '/avatars/avatar-58.svg', rotulo: 'Poodle' },
  { id: '59', url: '/avatars/avatar-59.svg', rotulo: 'Beagle' },
  { id: '60', url: '/avatars/avatar-60.svg', rotulo: 'Husky' },
  { id: '61', url: '/avatars/avatar-61.svg', rotulo: 'Salsicha' },
  { id: '62', url: '/avatars/avatar-62.svg', rotulo: 'Labrador' },
  { id: '63', url: '/avatars/avatar-63.svg', rotulo: 'Cabelo cacheado' },
  { id: '64', url: '/avatars/avatar-64.svg', rotulo: 'Com hijabe' },
  { id: '65', url: '/avatars/avatar-65.svg', rotulo: 'Tranças' },
  { id: '66', url: '/avatars/avatar-66.svg', rotulo: 'Ruiva sardenta' },
  { id: '67', url: '/avatars/avatar-67.svg', rotulo: 'Franja reta' },
  { id: '68', url: '/avatars/avatar-68.svg', rotulo: 'Careca e barba' },
  { id: '69', url: '/avatars/avatar-69.svg', rotulo: 'Com turbante' },
  { id: '70', url: '/avatars/avatar-70.svg', rotulo: 'Com óculos' },
  { id: '71', url: '/avatars/avatar-71.svg', rotulo: 'Pele com vitiligo' },
  { id: '72', url: '/avatars/avatar-72.svg', rotulo: 'Cabelo grisalho' },
  { id: '73', url: '/avatars/avatar-73.svg', rotulo: 'Robô astronave' },
  { id: '74', url: '/avatars/avatar-74.svg', rotulo: 'Robô industrial' },
  { id: '75', url: '/avatars/avatar-75.svg', rotulo: 'Robô simpático' },
  { id: '76', url: '/avatars/avatar-76.svg', rotulo: 'Robô tático' },
  { id: '77', url: '/avatars/avatar-77.svg', rotulo: 'Robô ciclópe' },
  { id: '78', url: '/avatars/avatar-78.svg', rotulo: 'Robô a vapor' },
  { id: '79', url: '/avatars/avatar-79.svg', rotulo: 'Robô assistente' },
  { id: '80', url: '/avatars/avatar-80.svg', rotulo: 'Robô angular' },
  { id: '81', url: '/avatars/avatar-81.svg', rotulo: 'Peixe palhaço' },
  { id: '82', url: '/avatars/avatar-82.svg', rotulo: 'Polvo' },
  { id: '83', url: '/avatars/avatar-83.svg', rotulo: 'Tartaruga marinha' },
  { id: '84', url: '/avatars/avatar-84.svg', rotulo: 'Cavalo-marinho' },
  { id: '85', url: '/avatars/avatar-85.svg', rotulo: 'Submarino' },
  { id: '86', url: '/avatars/avatar-86.svg', rotulo: 'Água-viva' },
  { id: '87', url: '/avatars/avatar-87.svg', rotulo: 'Caranguejo' },
  { id: '88', url: '/avatars/avatar-88.svg', rotulo: 'Peixe abissal' },
]

/** URL usada quando o usuário ainda não tem avatar definido. */
export const AVATAR_PADRAO_URL = AVATARES_PREDEFINIDOS[0].url
